### PR TITLE
Note that we always support .mjs

### PR DESCRIPTION
**Pull request by guybedford**
This was the only part I could find on this... let me know if I've missed anything.

### CODE REVIEW

**Comment by GeoffreyBooth** [comment]
Discussed in https://github.com/GeoffreyBooth/node-import-file-specifier-resolution-proposal/issues/5

**Comment by GeoffreyBooth** [comment]
I’m okay with this if I can be reassured that it won’t present issues in the future. My concern is that Node or loaders or other tools would have no way to definitively know the parse goal of a _package;_ like whether it’s expecting to be loaded as ESM, as CommonJS, or as either. Currently, that can be determined by reading the `package.json`. After this change, we lose that information about a package; they become ambiguous. We would know that a package _does_ export ESM, if it has an `exports` key, but not that it _doesn’t_ export ESM (since it might lack an `exports` key but still contain `.mjs` files).

@jkrems @bmeck @jdalton does such ambiguity in package metadata present any problems? Would this cause issues for loaders? Would there be any possibility of double-loading the same file (i.e. the same URL in two modes)? If no one has any concerns I’m okay with this, but it makes me nervous to allow this ambiguity in packages. It feels a lot like the ambiguity of `.js`, that spurred the creation of `.mjs` in the first place.

**Comment by bmeck** [comment]
@GeoffreyBooth we never want to state that a "package" only works in one way, the complexity around ambiguity is around files and specifiers. Due to history, `require()` will always make specifiers ambiguous, since any unknown specifier will be loaded as CJS, no matter how Node is configured. As such, the current text is around disambiguating files not around consumption methods. Files remain unambiguous with this change and I see no problem with it. `require()` will remain problematic for any new formats due to permanent ambiguity by design similar to `<script type=text/javascript>`. This does not appear to be a problem to add. We are not banning `.wasm` files etc in packages without an `exports` field or `mimes`, this falls in a similar category. By giving package authors the ability to control specifiers via things like `exports` we leave it to their control on how specifiers will be routed. It is therefore their responsibility to choose if some specifier is intended to be ambiguous for `import` (`require` is always :( ).

**Comment by GeoffreyBooth** [comment]
@bmeck Okay, and you don’t think we’ll need an unambiguous `package.json` for loaders? Or are you saying that it already _is_ unambiguous, in that we never need to know a package’s parse goal but rather only the parse goals of files, and that’s defined unambiguously per this proposal?

**Comment by bmeck** [comment]
@GeoffreyBooth I will state stronger than if I think we need to make package unambiguous, we cannot make an unambiguous package due to specifiers, how `require` works, and the addition of new types of supported modules. However, we can specify what the files are intended to be, and the format of a file is currently unambiguous in this proposal. As long as the queryable format of a given file is unambiguous there are no problems for loaders since the loader can always get a direct response on the expected format of a file.

**Comment by GeoffreyBooth** [comment]
@bmeck So I think when you say that the format of the package is ambiguous, I assume that's because even as the proposal is currently written Node only knows whether it exports ESM or not, or CommonJS or not; but whether it exports both (dual mode) cannot be known currently. Is that correct?

So we can allow this, and if for some reason packages need unambiguous package metadata we'll both need to revert this and add a mode field to `package.json` to specify all supported modes. Does that sound right? And I guess what you're saying is that loaders never need to know this about packages, since loaders work on files not packages, and the package metadata only matters on the context of working with specific files?

**Comment by GeoffreyBooth** [comment]
So I’m fine with merging this, but @bmeck I’m still not following what you’re saying, do you mind explaining it to me until I get it? 😄

So I’m not concerned about `require`. I know that `require` will always try to load a package as CommonJS. That’s just what `require` does. We’re not currently considering transparent import interop for `require` pulling in an ESM package.

We _can_ have unambiguous `package.json`s to define a package exports for use by `import` statements. I listed how above: `"exports"`/`"mode"` and no `"main"`, it’s ESM; `"main"` but no `"exports"`/`"mode"`, it’s CommonJS; `"main"` _and_ `"exports"`/`"mode"`, it’s dual-mode; none of the above, it’s CommonJS.
Merging in this PR _breaks_ the ability to have unambiguous packages, since now an `.mjs` file hiding inside a package that the `package.json` would say to be a CommonJS package makes the package either dual-mode or ESM.

So the question, I think, is whether it’s more important to have an `.mjs` file within a CommonJS package work as the user wants or instead to preserve the ability to determine the various parse goals that a package exports solely by parsing the `package.json` file. I was assuming that that ability would be useful, it not required, by loaders. Is that not the case?

And again, I’m only discussing within the context of ESM. Within CommonJS/`require`, nothing is changing and there are no “ESM” or “dual-mode” packages, everything is just attempted to be parsed as CommonJS (as far as I know). I don’t see how CommonJS’ legacy limitations affects how loaders should behave in an ESM or mixed-mode context.

**Comment by bmeck** [comment]
> We can have unambiguous package.jsons to define a package exports for use by import statements. I listed how above: "exports"/"mode" and no "main", it’s ESM; "main" but no "exports"/"mode", it’s CommonJS; "main" and "exports"/"mode", it’s dual-mode; none of the above, it’s CommonJS.
Merging in this PR breaks the ability to have unambiguous packages, since now an .mjs file hiding inside a package that the package.json would say to be a CommonJS package makes the package either dual-mode or ESM.

I'm saying that even if you say it is a given mode, it is not enforceable and non-meaningful. What files are acceptable in a given package "mode"? What happens when we add a new file type such as `.wasm`, does it only work in one mode? WASM is not ESM, why isn't the package in WASM mode?

I'm stating, that you *cannot* make it unambiguous even if you claim the package.json makes it unambiguous.

`.mjs` doesn't make packages ambiguous for the same reason `.json` and `.wasm` don't, packages are ambiguous by their nature of containing multiple formats.

**Comment by bmeck** [comment]
> I was assuming that that ability would be useful, it not required, by loaders. Is that not the case?

No, it is not really useful except for querying file information. It is not required either.

> And again, I’m only discussing within the context of ESM. Within CommonJS/require, nothing is changing and there are no “ESM” or “dual-mode” packages, everything is just attempted to be parsed as CommonJS (as far as I know). I don’t see how CommonJS’ legacy limitations affects how loaders should behave in an ESM or mixed-mode context.

Even within the context of purely ESM packages remain ambiguous since they could point to a `.coffee` file for their entrypoint etc.

**Pull request merged**
